server:
    port: 7001
javax:
  sql:
    DataSource:
      userDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          databaseName: "distribuida"
          user: "postgres"
          password: "12345"
